python3 ../hess_landscape_1d.py --dataset=CIFAR10 --data_path=/nfs/home/dgranziol/curvature/data/ --model=VGG16 --basis_path=/nfs/home/dgranziol/curvature/ckpts/c10/VGG16/SGDOPT/Hess-00300 --seed=1 --save_path=/nfs/home/dgranziol/curvature/ckpts/c10/VGG16/SGDOPT/hess_loss_results-d=1.npz --dist=1 --use_test
python3 ../hess_landscape_1d.py --dataset=CIFAR10 --data_path=/nfs/home/dgranziol/curvature/data/ --model=VGG16 --basis_path=/nfs/home/dgranziol/curvature/ckpts/c10/VGG16/SGDOPT/Hess-00300 --seed=1 --save_path=/nfs/home/dgranziol/curvature/ckpts/c10/VGG16/SGDOPT/hess_loss_results-d=2.npz --dist=2 --use_test
python3 ../hess_landscape_1d.py --dataset=CIFAR10 --data_path=/nfs/home/dgranziol/curvature/data/ --model=VGG16 --basis_path=/nfs/home/dgranziol/curvature/ckpts/c10/VGG16/SGDOPT/Hess-00300 --seed=1 --save_path=/nfs/home/dgranziol/curvature/ckpts/c10/VGG16/SGDOPT/hess_loss_results-d=0p5.npz --dist=0.5 --use_test
python3 ../hess_landscape_1d.py --dataset=CIFAR10 --data_path=/nfs/home/dgranziol/curvature/data/ --model=VGG16 --basis_path=/nfs/home/dgranziol/curvature/ckpts/c10/VGG16/SGDOPT/Hess-00300 --seed=1 --save_path=/nfs/home/dgranziol/curvature/ckpts/c10/VGG16/SGDOPT/hess_loss_results-d=0p25.npz --dist=0.25 --use_test



python3 ../hess_landscape_1d.py --dataset=CIFAR10 --data_path=/nfs/home/dgranziol/curvature/data/ --model=VGG16 --basis_path=/nfs/home/dgranziol/curvature/ckpts/c10/VGG16/SGDOPT/GN-00300 --seed=1 --save_path=/nfs/home/dgranziol/curvature/ckpts/c10/VGG16/SGDOPT/GN_loss_results-d=1.npz --dist=1 --use_test
python3 ../hess_landscape_1d.py --dataset=CIFAR10 --data_path=/nfs/home/dgranziol/curvature/data/ --model=VGG16 --basis_path=/nfs/home/dgranziol/curvature/ckpts/c10/VGG16/SGDOPT/GN-00300 --seed=1 --save_path=/nfs/home/dgranziol/curvature/ckpts/c10/VGG16/SGDOPT/GN_loss_results-d=2.npz --dist=2 --use_test
python3 ../hess_landscape_1d.py --dataset=CIFAR10 --data_path=/nfs/home/dgranziol/curvature/data/ --model=VGG16 --basis_path=/nfs/home/dgranziol/curvature/ckpts/c10/VGG16/SGDOPT/GN-00300 --seed=1 --save_path=/nfs/home/dgranziol/curvature/ckpts/c10/VGG16/SGDOPT/GN_loss_results-d=0p5.npz --dist=0.5 --use_test
python3 ../hess_landscape_1d.py --dataset=CIFAR10 --data_path=/nfs/home/dgranziol/curvature/data/ --model=VGG16 --basis_path=/nfs/home/dgranziol/curvature/ckpts/c10/VGG16/SGDOPT/GN-00300 --seed=1 --save_path=/nfs/home/dgranziol/curvature/ckpts/c10/VGG16/SGDOPT/GN_loss_results-d=0p25.npz --dist=0.25 --use_test
